### ISSUE TITLE
Error in odometry suddenly.

### ISSUE THREAD

**Issue by jacob-02** [AdityaVaradaraj/EKF-PID-Diff-Drive#1]
![image](https://github.com/AdityaVaradaraj/EKF-PID-Diff-Drive/assets/74947682/091bd90d-ea67-47e9-b046-3240d9ab2027)

The pose estimate of the robot suddenly changes when the robot is making a circular path. The green points are the set of points that represent the EKF estimate of the position using IMU and Odom. The red is the wheel odometry from gazebo. 

This is repeatedly observed when the robot's yaw changes from -pi to pi or vice versa.

Any idea why this could be the case and what should I do to correct this?

Thank you in advance

**Comment by AdityaVaradaraj** [comment]
Try limiting state_[2] + omega*delta, i.e., new angle to -pi to pi before prediction update. You can check once if that's what is causing the issue.

**Comment by jacob-02** [comment]
https://github.com/AdityaVaradaraj/EKF-PID-Diff-Drive/pull/2

This PR should solve the issue

**Comment by AdityaVaradaraj** [comment]
Thanks @jacob-02
